version: "3.9"

x-deploy-default: &deploy-default
  restart_policy: {condition: on-failure}
  update_config:
    order: start-first
    parallelism: 1
    delay: 10s

services:
  # ────────── Backend ──────────
  backend:
    image: yoonjaeko/express-backend:1.06
    env_file: .env
    expose: ["8080"]
    depends_on:
      - redis
    healthcheck:
      test: ["CMD", "wget", "--spider", "--quiet", "http://localhost:8080/health"]
      interval: 30s
      retries: 3
    deploy: {<<: *deploy-default, replicas: 3}

secrets:
  mystack_fullchain:
    external: true
  mystack_privkey:
    external: true
