version: "3.9"

services:
  # ────────────── 개발·운영 공통 ──────────────
  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"        # 호스트에도 그대로 노출
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      retries: 3

  # ────────────── 운영 전용(backend) ──────────────
  backend:
    build: .
    container_name: express-backend
    env_file: .env
    expose:
      - "8080"
    depends_on:
      redis:
        condition: service_healthy
    profiles: ["prod"]     # ★ prod 프로파일에만 포함

  # ────────────── 운영 전용(nginx) ──────────────
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/sites-available:/etc/nginx/sites-available:ro
      - ./nginx/sites-enabled:/etc/nginx/sites-enabled:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      backend:
        condition: service_started
    profiles: ["prod"]     # ★ prod 프로파일에만 포함
