apiVersion: v1
kind: Service
metadata:
  name: express-backend-svc
  namespace: mystack
  labels:
    app: express-backend
spec:
  selector:
    app: express-backend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30080    # 외부(로컬)에서 접속할 포트 (30000~32767 사이)
  type: NodePort
