name: CI/CD – Express Backend Only

on:
  push:
    branches:
      - master       # ← master 브랜치에 푸시될 때만 실행

jobs:
  deploy-backend:
    runs-on: ubuntu-latest
    env:
      REGISTRY: ${{ secrets.REGISTRY }}
      IMAGE_NAME: express-backend
      STACK_NAME: mystack
      SSH_HOST: ${{ secrets.SSH_HOST }}
      SSH_USER: raspi      # ← SSH 사용자명 raspi
      SSH_KEY: ${{ secrets.SSH_KEY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to container registry
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Express Backend image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}

      - name: Update only Express Backend service
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ env.SSH_HOST }}
          username: ${{ env.SSH_USER }}
          key: ${{ env.SSH_KEY }}
          script: |
            TAG=${{ github.sha }}
            sudo docker pull $REGISTRY/$IMAGE_NAME:$TAG
            sudo docker service update \
              --with-registry-auth \
              --image $REGISTRY/$IMAGE_NAME:$TAG \
              ${STACK_NAME}_backend
