name: CI/CD – Express Backend Only

on:
  push:
    branches:
      - master

jobs:
  deploy-backend:
    runs-on: ubuntu-latest

    env:
      REGISTRY: yoonjaeko
      IMAGE_NAME: express-backend
      STACK_NAME: mystack
      SSH_HOST: ${{ secrets.SSH_HOST }}
      SSH_USER: raspi
      SSH_KEY: ${{ secrets.SSH_KEY }}
      SSH_PORT: ${{ secrets.SSH_PORT }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          install: true
          use: true
          driver-opts: |
            image=moby/buildkit:master

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push multi-arch image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}

      - name: Update only Express Backend service
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ env.SSH_HOST }}
          port: ${{ env.SSH_PORT }}
          username: ${{ env.SSH_USER }}
          key: ${{ env.SSH_KEY }}
          script: |                    # ← 이 줄부터 with: 안으로!
            TAG=${{ github.sha }}
            REGISTRY=${{ env.REGISTRY }}
            IMAGE_NAME=${{ env.IMAGE_NAME }}
            STACK_NAME=${{ env.STACK_NAME }}

            sudo docker pull $REGISTRY/$IMAGE_NAME:$TAG
            sudo docker service update \
              --with-registry-auth \
              --image $REGISTRY/$IMAGE_NAME:$TAG \
              ${STACK_NAME}_backend
